* Nokia 105(2G) Note

I buy a new nokia 105 (not 4G) from taobao:

https://www.nokia.com/phones/en_int/nokia-105?sku=1GF019CPA2L05

https://www.nokia.com/phones/en_int/nokia-105/specs?sku=1GF019CPA2L05

phone guide:

https://www.nokia.com/phones/en_int/support/api/pdf/nokia-105-user-guide?locale=en-US

It cost me 139 RMB.

If the price of the machine you bought is more than 170 RMB, Probably not 2G version.

** device info

enter code:

#+BEGIN_SRC text
*#0000#*
#+END_SRC

my device:

#+BEGIN_SRC
Nokia 105
11.00.17.00
12-04-2023
TA-1557
(C)Nokia
...
#+END_SRC

reference:

https://www.youtube.com/watch?v=Lvvejc-M0bI

** boot key

I found boot key is:

#+BEGIN_SRC
*
#+END_SRC

when hold boot key then bootup phone, device will into flash mode.

** usb

plug on computer, it provide a usb 1.1 device:

#+BEGIN_SRC
[115415.430562] usb 1-1.8.6: new full-speed USB device number 22 using ehci-pci
#+END_SRC

when we shutdown the phone:

#+BEGIN_SRC
[119569.012805] usb 1-1.8.6: new full-speed USB device number 24 using ehci-pci
[119569.121561] usb 1-1.8.6: New USB device found, idVendor=1782, idProduct=4d00, bcdDevice= 0.01
[119569.121581] usb 1-1.8.6: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[119573.907466] usb 1-1.8.6: USB disconnect, device number 24
#+END_SRC

lsusb:

#+BEGIN_SRC
Bus 001 Device 032: ID 1782:4d00 Spreadtrum Communications Inc.
#+END_SRC

it look like flash mode for this phone :)

it use generic usb serial driver on linux (not working, need capture usb data from windows) :

#+BEGIN_SRC shell
modprobe ftdi_sio
echo 1782 4d00 > /sys/bus/usb-serial/drivers/generic/new_id
#+END_SRC

reference:

https://github.com/ilyakurdyukov/spreadtrum_flash/blob/fa20bcc314c931e0c790ba62ab028706d802ccc3/README.md?plain=1#L25

** screen

1. ST7735?

https://github.com/Abhishektiwari7/lcd_nokia_105_drivers/

I'm not sure it's this one, when I buy a new one, take a logic analyzer to capture the data on the screen.

** firmware

flash is builtin in soc :(

TODO: extract firmware form real phone.

** chip

Spreadtrum SC6531E is mian soc.

TI RTM7276F is power ic.

** end

reference:

https://treexy.com/products/driver-fusion/database/ports-com-lpt-serial/spreadtrum/sci-usb2serial/

https://www.getdroidtips.com/download-latest-spreadtrum-usb-drivers/

https://blog.masoomyf.com/2017/12/download-spreadtrum-mtk-driver-64bit.html

https://forum.gsmhosting.com/vbb/f1110/error-nokia-c3-ta-1298-solved-3103747/

https://forum.gsmhosting.com/vbb/f723/sci-usb-serial-driver-win7-64bit-1924923/

https://techprolonged.com/2015/03/install-mediatek-mt65xx-usb-vcom-drivers-for-windows-all/

https://forum.gsmhosting.com/vbb/f1110/nokia-g21-error-42-solved-3106775/

https://github.com/HowToLoveChina/InkCaseMe/wiki/InkCase--Plus

https://github.com/TomKing062/CVE-2022-38694_unlock_bootloader/wiki/

https://research.nccgroup.com/2022/09/02/theres-another-hole-in-your-soc-unisoc-rom-vulnerabilities/

https://github.com/cocktail828/dloader

https://naijarom.com/tag/miracle-box

https://firmwarefile.com/nokia-105-2019-ta-1174

https://androiddatahost.com/fgh56

https://www.firmwarexbd.com/2022/07/nokia-220-ta-1279-clone-mt6260-flash-file.html

https://www.firmwarexbd.com/2020/03/miracle-box-282-thunder-edition-crack.html

https://www.firmwarexbd.com/2020/03/download-mediatek-usb-vcom-drivers.html

https://www.firmwarexbd.com/2022/06/nokia-106-ta-1114-clone-mt6260-flash-file.html

https://www.firmwarexbd.com/2022/06/maximum-mb10-flash-file-version-3.html

https://androidfilehost.com/?fid=15664248565197191315

https://www.youtube.com/watch?v=U8y-UnvvI4k

https://www.alltipsandflashbangla.com/2017/08/flashtoolv5142000-mt6261china-keypad.html

https://www.dr-lex.be/hardware/china_phone_flashing.html

https://www.cnx-software.com/2015/11/24/no-1-d3-smartwatch-review/

https://www.kosagi.com/w/index.php?title=Fernvale_Main_Page

https://forum.xda-developers.com/t/mt6261-and-mt6260-source-code-discussion.3819263/

https://forum.xda-developers.com/t/help-need-firmware-for-mt6260ma-a1-smartwatch.3872430/

https://www.bunniestudios.com/blog/?p=4297

https://github.com/ihewitt/ivrtrack/blob/main/util/dump.c

https://github.com/ilyakurdyukov/mediatek_flash.git

https://postmarketos.org/blog/2018/04/14/lowlevel/

https://github.com/sutajiokousagi/fernvale-nuttx

https://github.com/ilyakurdyukov/fpdoom

https://www.gsmarena.com/nokia_105_(2019)-9773.php

https://www.datasheet4u.com/datasheet-pdf/Spreadtrum/SC6531E/pdf.php?id=1455703

https://github.com/ilyakurdyukov/spreadtrum_flash

https://github.com/Iscle/mksprdpac/blob/master/main.c

https://androiddatahost.com/hgf64

https://forum.gsmhosting.com/vbb/f723/spd-sc6531-dead-solution-1751715/

https://github.com/ilyazx/bzpwork

https://github.com/armijnhemel/binaryanalysis-ng

https://www.martview-forum.com/threads/sc6533g-and-sc6531e-all-tested-files-here.10615/

https://chronovir.us/2021/12/18/Opus-Spreadtrum/
