* Nokia 105(2G) Note

I buy a new nokia 105 (not 4G) from taobao:

https://www.nokia.com/phones/en_int/nokia-105?sku=1GF019CPA2L05

https://www.nokia.com/phones/en_int/nokia-105/specs?sku=1GF019CPA2L05

phone guide:

https://www.nokia.com/phones/en_int/support/api/pdf/nokia-105-user-guide?locale=en-US

It cost me 139 RMB.

If the price of the machine you bought is more than 170 RMB, Probably not MTK's 2G chip.

** machine picture

TODO

** device info

enter code:

#+BEGIN_SRC text
*#0000#*
#+END_SRC

my device:

#+BEGIN_SRC
Nokia 105
11.00.17.00
12-04-2023
TA-1557
(C)Nokia
...
#+END_SRC

reference:

https://www.youtube.com/watch?v=Lvvejc-M0bI

** boot key

I found boot key is:

#+BEGIN_SRC
*
#+END_SRC

when hold boot key then bootup phone, device will into flash mode.

** usb

plug on computer, it provide a usb 1.1 device:

#+BEGIN_SRC
[115415.430562] usb 1-1.8.6: new full-speed USB device number 22 using ehci-pci
#+END_SRC

when we shutdown the phone:

#+BEGIN_SRC
[119569.012805] usb 1-1.8.6: new full-speed USB device number 24 using ehci-pci
[119569.121561] usb 1-1.8.6: New USB device found, idVendor=1782, idProduct=4d00, bcdDevice= 0.01
[119569.121581] usb 1-1.8.6: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[119573.907466] usb 1-1.8.6: USB disconnect, device number 24
#+END_SRC

lsusb:

#+BEGIN_SRC
Bus 001 Device 032: ID 1782:4d00 Spreadtrum Communications Inc.
#+END_SRC

it look like flash mode for this phone :)

it use generic usb serial driver on linux (not working, need capture usb data from windows) :

#+BEGIN_SRC shell
modprobe ftdi_sio
echo 1782 4d00 > /sys/bus/usb-serial/drivers/generic/new_id
#+END_SRC

reference:

https://github.com/ilyakurdyukov/spreadtrum_flash/blob/fa20bcc314c931e0c790ba62ab028706d802ccc3/README.md?plain=1#L25

** screen

https://github.com/Abhishektiwari7/lcd_nokia_105_drivers/

I'm not sure it's this one, when I buy a new one, take a logic analyzer to capture the data on the screen.

** firmware

TODO: extract firmware form real phone.

** chip

may be Mediatek MT6261D, Wait till I buy another one for reverse engineering.

** end

reference:

https://treexy.com/products/driver-fusion/database/ports-com-lpt-serial/spreadtrum/sci-usb2serial/

https://www.getdroidtips.com/download-latest-spreadtrum-usb-drivers/

https://blog.masoomyf.com/2017/12/download-spreadtrum-mtk-driver-64bit.html

https://forum.gsmhosting.com/vbb/f1110/error-nokia-c3-ta-1298-solved-3103747/

https://forum.gsmhosting.com/vbb/f723/sci-usb-serial-driver-win7-64bit-1924923/

https://techprolonged.com/2015/03/install-mediatek-mt65xx-usb-vcom-drivers-for-windows-all/

https://forum.gsmhosting.com/vbb/f1110/nokia-g21-error-42-solved-3106775/

https://github.com/HowToLoveChina/InkCaseMe/wiki/InkCase--Plus

https://github.com/TomKing062/CVE-2022-38694_unlock_bootloader/wiki/

https://research.nccgroup.com/2022/09/02/theres-another-hole-in-your-soc-unisoc-rom-vulnerabilities/

https://github.com/cocktail828/dloader

https://naijarom.com/tag/miracle-box

https://firmwarefile.com/nokia-105-2019-ta-1174

https://androiddatahost.com/fgh56

https://www.firmwarexbd.com/2022/07/nokia-220-ta-1279-clone-mt6260-flash-file.html

https://www.firmwarexbd.com/2020/03/miracle-box-282-thunder-edition-crack.html

https://www.firmwarexbd.com/2020/03/download-mediatek-usb-vcom-drivers.html

https://www.firmwarexbd.com/2022/06/nokia-106-ta-1114-clone-mt6260-flash-file.html

https://www.firmwarexbd.com/2022/06/maximum-mb10-flash-file-version-3.html

https://androidfilehost.com/?fid=15664248565197191315

https://www.youtube.com/watch?v=U8y-UnvvI4k

https://www.alltipsandflashbangla.com/2017/08/flashtoolv5142000-mt6261china-keypad.html

https://ia801603.us.archive.org/16/items/mediatek_202304/MT6261D_GSM_GPRS_SOC_Processor_Technical_Brief_v1.01.pdf

https://datasheet4u.com/datasheet-pdf/MEDIATEK/MT6261D/pdf.php?id=1266527

https://www.alldatasheet.com/view.jsp?Searchword=MT6260

https://www.dr-lex.be/hardware/china_phone_flashing.html

https://www.cnx-software.com/2015/11/24/no-1-d3-smartwatch-review/

https://forum.xda-developers.com/t/universal-readback-extractor-for-mtk-feature-watchphones.3289272/

https://www.kosagi.com/w/index.php?title=Fernvale_Main_Page

https://forum.xda-developers.com/t/universal-readback-extractor-for-mtk-feature-watchphones.3289272/

https://forum.xda-developers.com/t/mt6261-and-mt6260-source-code-discussion.3819263/

https://forum.xda-developers.com/t/help-need-firmware-for-mt6260ma-a1-smartwatch.3872430/

https://forum.xda-developers.com/t/smartchinares-mt6260-and-mt6261-language-and-mediaeditor.3610972/

https://forum.xda-developers.com/t/dz09-mtk6260-and-6261-editor.3834122/

https://forum.xda-developers.com/t/mtk-feature-watchphones-firmware-collection-6260a-6261da-2502a-2502c.3306203/page-2

https://forum.xda-developers.com/tags/mt6260/

https://forum.xda-developers.com/tags/mt6261/

https://forum.gsmhosting.com/vbb/f723/tutorial-mtk-6260-625a-usb-method-1804948/

https://www.open-electronics.org/reverse-engineering-mediatek-mt6260-the-fernvale-project-from-bunnie-wang/

https://www.bunniestudios.com/blog/?p=4297

https://hackaday.com/tag/mt6260/

https://forum.gsmhosting.com/vbb/f781/mtk-latest-factory-flash-tool-support-mt6260-1662646/

https://forum.gsmhosting.com/vbb/f820/avengers-generic-mtk-tool-support-flash-bin-files-mt6260-2136579/

https://github.com/MediatekInfo/DZ09

https://github.com/waybyte/tool-pymtkflasher

https://github.com/Wiz-IO/wizio-mtk

https://github.com/xobs/fernly

https://github.com/NikolayPetukhov/qemu-mtk

https://github.com/ihewitt/ivrtrack/blob/main/util/dump.c

https://github.com/ilyakurdyukov/mediatek_flash.git

https://postmarketos.org/blog/2018/04/14/lowlevel/

https://github.com/sutajiokousagi/fernvale-nuttx
